### ISSUE TITLE
[To Do] DCT files

### ISSUE THREAD

**Issue by maffeyl** [AmyOlex/Chrono#28]
If no DCT file exists, either try to infer doctime from text or assume it's today or something.

**Comment by maffeyl** [comment]
Added a check for .dct files to the Luke branch, just uses today's date if there aren't any found and that seems to be working fine, but won't be very useful long term.

**Comment by AmyOlex** [comment]
Agreed.  Currently, Chrono depends on the DCT files.  I think inferring Doc time from the document is probably another whole program and problem.  I've closing this for now with the understanding that this issue is another project entirely and should be implemented eventually.
