### ISSUE TITLE
AM entities not being added

### ISSUE THREAD

**Issue by AmyOlex** [AmyOlex/Chrono#38]
I'm not sure how tired I was when I wrote the AMPM parsing, but it is a bit messed up.  It never adds an entity if it is AM, only for PM.  I'm re-writing and fixing this now.

**Comment by AmyOlex** [comment]
Fixed this issue!  I edited the build-AMPM method so that it now adds the AM entities.  However, this created false positives, such as the word "am".  Therefore I also edited the sub-interval linking to 1) add these AMPM properties to the hour entities, and 2) to delete an AM entity if there is no hour associated with it.  This is now getting about half, but we are still missing about half of the proper linking, so more debugging needs to be done.

**Comment by maffeyl** [comment]
Yeah, I noticed that we weren't doing AM before and I just figured it was because there weren't very many in the newswire corpus so then we didn't have to deal with false positive "am".
