### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by maffeyl** [AmyOlex/Chrono#49]
Do we want to add a way to automate requirements installation?

**Comment by AmyOlex** [comment]
Yes, that would be nice.  I just haven't had time.  Do you want to work on
that?  It would make it easier for others to use.



*Amy L. Olex*
Bioinformatics Specialist
C. Kenneth and Dianne Wright Center for Clinical and Translational Research

Virginia Commonwealth University
1200 E. Clay Street
P.O. Box 980261
Richmond, VA 23298

Phone: 804-828-1621
Fax: 804-628-4723

*Please Remember!  If my consulatation or services have contributed towards
a manuscript, grant, or other type of publication please cite the CTSA
Grant* *UL1TR002649, which funds all services offered by the CCTR.*

**Comment by maffeyl** [comment]
Sure!

**Comment by maffeyl** [comment]
We already had a setup.py file, I just needed to update it and the README, tested and it appears to be working fine.
